### ISSUE TITLE
Exception: cvCreateCameraCapture() Error: Could not create camera capture.

### ISSUE THREAD

**Issue by nebeinstein** [WPIRoboticsProjects/GRIP#125]
What were the actions performed prior to this error appearing?

> yeah uh uh type - Jonathan Leitschuh

tried to use a webcam on windows

## System Info:

Property Name | Property 
 ----- | -----
javafx.version | 8.0.66
java.runtime.name | Java(TM) SE Runtime Environment
java.vm.version | 25.66-b17
java.vm.vendor | Oracle Corporation
java.vm.name | Java HotSpot(TM) 64-Bit Server VM
java.runtime.version | 1.8.0_66-b17
java.awt.graphicsenv | sun.awt.Win32GraphicsEnvironment
javafx.runtime.version | 8.0.66-b17
os.name | Windows 10
os.version | 10.0
os.arch | amd64
file.encoding | windows-1252
java.vm.info | mixed mode
java.version | 1.8.0_66
sun.arch.data.model | 64
sun.cpu.endian | little

## Stack Trace:
```java
java.io.IOException: A problem occurred trying to start the frame grabber for Webcam 0
	at edu.wpi.grip.core.sources.CameraSource.startVideo(CameraSource.java:97)
	at edu.wpi.grip.core.sources.CameraSource.<init>(CameraSource.java:68)
	at edu.wpi.grip.core.sources.CameraSource.<init>(CameraSource.java:43)
	at edu.wpi.grip.ui.pipeline.AddSourceView.lambda$null$39(AddSourceView.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.bytedeco.javacv.FrameGrabber$Exception: cvCreateCameraCapture() Error: Could not create camera capture.
	at org.bytedeco.javacv.OpenCVFrameGrabber.start(OpenCVFrameGrabber.java:179)
	at edu.wpi.grip.core.sources.CameraSource.startVideo(CameraSource.java:95)
	... 6 more

```

**Comment by JLLeitschuh** [comment]
Closed by #166
