### ISSUE TITLE
GRIP should not prompt me to use webcams I don't have

### ISSUE THREAD

**Issue by nightpool** [WPIRoboticsProjects/GRIP#134]
Trying to use any webcam other then 0 when your system only has 1 webcam throws an exception. Ideally GRIP would enumerate the webcams on your system and only present ones that *won't* make it crash.

## Stack Trace:
```java
java.io.IOException: A problem occurred trying to start the frame grabber for Webcam 1
	at edu.wpi.grip.core.sources.CameraSource.startVideo(CameraSource.java:97)
	at edu.wpi.grip.core.sources.CameraSource.<init>(CameraSource.java:68)
	at edu.wpi.grip.core.sources.CameraSource.<init>(CameraSource.java:43)
	at edu.wpi.grip.ui.pipeline.AddSourceView.lambda$null$39(AddSourceView.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.bytedeco.javacv.FrameGrabber$Exception: cvCreateCameraCapture() Error: Could not create camera capture.
	at org.bytedeco.javacv.OpenCVFrameGrabber.start(OpenCVFrameGrabber.java:179)
	at edu.wpi.grip.core.sources.CameraSource.startVideo(CameraSource.java:95)
	... 6 more

```

**Comment by JLLeitschuh** [comment]
Unfortunately, there doesn't seem to be any way to get this information out of the library we are using.
I agree that this is a feature that we need to figure out.

**Comment by AustinShalit** [comment]
We could try to create the source and if it fails to start assume there is no camera attached.

**Comment by SamCarlberg** [comment]
It will also crash if a webcam is present but another process is using it (at least on my macbook air) so that might not be the best way of doing it

**Comment by JLLeitschuh** [comment]
We do this currently.
The crashing, if due to a segfault, we can't do anything about.

**Comment by AustinShalit** [comment]
I have added a wontfix label to this.  It is important that GRIP gives access to cameras that do not exist for different environments.
