### ISSUE TITLE
Uncaught Exception in Thread

### ISSUE THREAD

**Issue by SargonRobotics** [WPIRoboticsProjects/GRIP#511]
I am trying to deploy a previously stable GRIP file to the roborio. 

GRIP: 1.2
Network Tables: On roborio
OS: Windows 7
Camera: USB Microsoft LifeCam 3000

Here's the error I'm getting:
SEVERE: Uncaught Exception on thread Thread[main,5,main]
com.thoughtworks.xstream.converters.ConversionException: Cannot connect sockets : Cannot connect sockets
---- Debugging information ----
message             : Cannot connect sockets
cause-exception     : java.lang.IllegalArgumentException
cause-message       : Cannot connect sockets
class               : edu.wpi.grip.core.Connection
required-type       : edu.wpi.grip.core.Connection
converter-type      : edu.wpi.grip.core.serialization.ConnectionConverter
line number         : 112
class[1]            : java.util.HashSet
converter-type[1]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
class[2]            : edu.wpi.grip.core.Pipeline
converter-type[2]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
version             : 1.2.0
-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:71)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.addCurrentElementToCollection(CollectionConverter.java:98)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:91)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:85)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:80)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:480)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:412)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1206)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1190)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1061)
	at edu.wpi.grip.core.serialization.Project.open(Project.java:68)
	at edu.wpi.grip.core.serialization.Project.open(Project.java:62)
	at edu.wpi.grip.core.Main.start(Main.java:61)
	at edu.wpi.grip.core.Main.main(Main.java:43)
Caused by: java.lang.IllegalArgumentException: Cannot connect sockets
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at edu.wpi.grip.core.Connection.<init>(Connection.java:37)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:86)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at com.google.inject.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:770)
	at com.sun.proxy.$Proxy8.create(Unknown Source)
	at edu.wpi.grip.core.serialization.ConnectionConverter.unmarshal(ConnectionConverter.java:58)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	... 24 more

VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV
VIDEOIO ERROR: V4L: setting property #16 is not supported
VIDIOC_STREAMON: Bad file descriptor
VIDIOC_STREAMON: Bad file descriptor
Feb 15, 2016 4:44:17 PM edu.wpi.grip.core.Main onExceptionEvent
SEVERE: Failed to start
org.bytedeco.javacv.FrameGrabber$Exception: cvGrabFrame() Error: Could not grab frame. (Has start() been called?)
	at org.bytedeco.javacv.OpenCVFrameGrabber.start(OpenCVFrameGrabber.java:214)
	at edu.wpi.grip.core.sources.CameraSource$1.startUp(CameraSource.java:210)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:54)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:100)
	at java.lang.Thread.run(Thread.java:745)

I have tried: 
power cycling
changing USB ports (both on Rio and laptop)
googling it (all I found was this: http://www.chiefdelphi.com/forums/showthread.php?t=142480)
The error was in the deploy console

**Comment by SargonRobotics** [comment]
Fixed! Looked back at the pipeline and some of the inputs were receiving from the wrong point. Not sure how it happened, but an edit and a redeploy fixed the issue.
