### ISSUE TITLE
Axis Camera not working

### ISSUE THREAD

**Issue by Szewczukm** [WPIRoboticsProjects/GRIP#539]
Started receiving this error about 3 days ago while testing out vision on our test robot.  Not sure what the issue is but haven't been able to diagnose it yet.  Here is the stack trace given to me.

```
Thread[JavaFX Application Thread,5,main] threw an exception
```

## Stack Trace:
```java
java.lang.NullPointerException
	at edu.wpi.grip.ui.components.ExceptionWitnessResponderButton.getPopover(ExceptionWitnessResponderButton.java:163)
	at edu.wpi.grip.ui.components.ExceptionWitnessResponderButton.lambda$onExceptionEvent$1(ExceptionWitnessResponderButton.java:179)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)

```
## System Info:

Property Name | Property 
 ----- | -----
GRIP Version | 1.3.0-rc2
java.version | 1.8.0_66
javafx.version | 8.0.66
os.name | Windows 7
os.version | 6.1
os.arch | amd64

```

**Comment by JLLeitschuh** [comment]
I know why this is a problem. This is a race condition between the event bus responding to an exception and the object actually being added to the scene.
