### ISSUE TITLE
Trying to use cscore on Raspi as input to Grip on Windows machine.

### ISSUE THREAD

**Issue by JimHofm52** [WPIRoboticsProjects/GRIP#895]
Thread[JavaFX Application Thread,5,main] threw an exception
## Stack Trace:
```java
java.lang.IllegalStateException: Can not start while in state STARTING. Must be in one of states: NEW, FAILED, TERMINATED
	at edu.wpi.grip.core.util.service.AutoRestartingService.startAsync(AutoRestartingService.java:123)
	at edu.wpi.grip.core.util.service.AutoRestartingService.startAsync(AutoRestartingService.java:108)
	at edu.wpi.grip.core.sources.CameraSource.startAsync(CameraSource.java:270)
	at edu.wpi.grip.core.sources.CameraSource.startAsync(CameraSource.java:46)
	at edu.wpi.grip.ui.components.StartStoppableButton.lambda$new$1(StartStoppableButton.java:64)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(CompositeEventHandler.java:282)
	at com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(CompositeEventHandler.java:98)
	at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:223)
	at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:180)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)

```
## System Info:

Property Name | Property
 ----- | -----
GRIP Version | v1.5.2
java.version | 1.8.0_101
javafx.version | 8.0.101
os.name | Windows 10
os.version | 10.0
os.arch | amd64

Please describe what actions we can take to reproduce the bug you found, including the error message.

**Comment by JLLeitschuh** [comment]
Can you describe the steps required to reproduce this?

**Comment by JimHofm52** [comment]
I am using the FRC example.  I can run the code on a Raspi 3B+ with the
lastest Streach.  I can see the frames at localhost:1185 & 1186.  I can
remotely see the frames in my browser at ipAdr:1185 & 1186.  However, when
I enter the ipAdr:1185 in Grip it indicates the program threw an error.  I
did have to use cscore 3.1.0 since 3.2.0 would not compile.

I was able to get the camera on Grip using Motion from the Sarrow Bird cam
example but I'd like to use cscore if possible.

Here is a Chief Delphi Discussion:
https://www.chiefdelphi.com/forums/showthread.php?t=161771

**Comment by JimHofm52** [comment]
Someone posted use, RPi,ip.adr:1185/?action=stream as the input to a Grip
input source.  It appears to work.

My question now is does NTPublish ContoursReport create a local
networkTable that can be accessed by OutlineViewer?  How?

Thanks.

**Comment by JLLeitschuh** [comment]
@SamCarlberg Does GRIP work with the newest version of Network Tables or is the protocol incompatible?

**Comment by SamCarlberg** [comment]
It's compatible.

@JimHofm52 You need to set the NetworkTable server address in `Tools > Settings`. It defaults to `roborio-0-frc.local`. If you're using OutlineViewer in server mode, set the address in GRIP to `localhost`. Keep in mind that GRIP will only connect to the server if you have an NTPublish operation in the pipeline with its input connected

**Comment by SamCarlberg** [comment]
You have GRIP configured to connect to `roborio-86-frc.local` as the host running the NetworkTables server. This won't work if the server you _want_ to connect to is running on `localhost`.

You also have GRIP set up to host its internal HTTP server on port 1735. That's the default server port for NetworkTables. I'm surprised you're able to have that configured at all - GRIP usually crashes if you set the HTTP server port to one already in use.

What's actually running the NetworkTable server? The instance of OutlineViewer in the screenshot is in client mode

**Comment by JimHofm52** [comment]
I have tried localhost on Grip and outlineviewer in server mode but maybe
not together.  I'll try again.

SOOooo, what I'm hearing, Grip is not the NT server.  Grip NTPublish xyz
pushes the values to a NT server which is the outlineViewer..  Clear as mud.

I'll give it a try.

Thanks.

**Comment by SamCarlberg** [comment]
> Grip is not the NT server

Correct. It is a NetworkTables _client_. Tne NTPublish operations require a NetworkTables server to publish to.

Putting OutlineViewer in server mode and setting the NetworkTables server address in GRIP to `localhost` should solve your problem

**Comment by JimHofm52** [comment]
Just wanted to let you know that did solve my issue.  Now I just need to
get NT working on the PI.

Thanks again,

Jim
