### ISSUE TITLE
Crash on loading project when webcam does not exist

### ISSUE THREAD

**Issue by nickschatz** [WPIRoboticsProjects/GRIP#925]
I have a project that uses the same pipeline to process a Multi-image source (for offline tuning) and from a webcam (online tuning.) When I load the project without the webcam attached (which is normally listed as /dev/video2 and is webcam 2 in GRIP,) the program crashes with the following error.

In theory the program should handle a disappearing webcam gracefully and not crash the program (also preventing me from modifying the project and deleting the webcam source, which would allow me to work around the error.)

Thread[Project Open Thread,5,main] threw an exception
## Stack Trace:
```java
com.thoughtworks.xstream.converters.ConversionException: Error deserializing socket
---- Debugging information ----
message             : Error deserializing socket
cause-exception     : java.lang.IndexOutOfBoundsException
cause-message       : index (1) must be less than size (1)
class               : edu.wpi.grip.core.sockets.Socket
required-type       : edu.wpi.grip.core.sockets.Socket
converter-type      : edu.wpi.grip.core.serialization.SocketConverter
line number         : 518
class[1]            : edu.wpi.grip.core.Connection
converter-type[1]   : edu.wpi.grip.core.serialization.ConnectionConverter
class[2]            : java.util.HashSet
converter-type[2]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
class[3]            : edu.wpi.grip.core.Pipeline
converter-type[3]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
version             : v1.5.2
-------------------------------
	at edu.wpi.grip.core.serialization.SocketConverter.unmarshal(SocketConverter.java:152)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at edu.wpi.grip.core.serialization.ConnectionConverter.unmarshal(ConnectionConverter.java:45)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:73)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.addCurrentElementToCollection(CollectionConverter.java:98)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:91)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:85)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:80)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:503)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:429)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1230)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1214)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1085)
	at edu.wpi.grip.core.serialization.Project.open(Project.java:122)
	at edu.wpi.grip.core.serialization.Project.open(Project.java:101)
	at edu.wpi.grip.ui.MainWindowController.lambda$openProject$5(MainWindowController.java:197)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: index (1) must be less than size (1)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1177)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1159)
	at com.google.common.collect.SingletonImmutableList.get(SingletonImmutableList.java:41)
	at edu.wpi.grip.core.serialization.SocketConverter.unmarshal(SocketConverter.java:127)
	... 29 more

```
## System Info:

Property Name | Property
 ----- | -----
GRIP Version | v1.5.2
java.version | 1.8.0_102
javafx.version | 8.0.102
os.name | Linux
os.version | 4.19.23-1-MANJARO
os.arch | amd64

```

**Comment by nickschatz** [comment]
Can't reproduce on d8cabe8.
