### ISSUE TITLE
Exception on Removal of Gpu Operation

### ISSUE THREAD

**Issue by TheTripleV** [WPIRoboticsProjects/GRIP#949]
Steps to Reproduce:

1. Add a webcam/video source
2. Make it visible
3. Add a blur operation (I just left it at box blur)
4. Connect the blur's input to the source
5. Make the blur visible
6. Set the blur to gpu preferred
7. Remove the blur
8. Exception occurs

Thread[JavaFX Application Thread,5,main] threw an exception
## Stack Trace:
```java
java.lang.NullPointerException: This pointer address is NULL.
	at org.bytedeco.javacpp.opencv_core$Mat.channels(Native Method)
	at edu.wpi.grip.ui.util.ImageConverter.convert(ImageConverter.java:58)
	at edu.wpi.grip.ui.preview.ImageSocketPreviewView.lambda$convertImage$0(ImageSocketPreviewView.java:32)
	at edu.wpi.grip.ui.util.GripPlatform.lambda$onJavaFXRunnerEvent$0(GripPlatform.java:74)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
## System Info:

Property Name | Property
 ----- | -----
GRIP Version | v1.5.2-44-g37733eae3-cuda
java.version | 11.0.2
javafx.version | 11
os.name | Windows 10
os.version | 10.0
os.arch | amd64

os.build | 1903 | 18362.113
cuda.version | 10.0.130 (2018/8/25)

**Comment by SamCarlberg** [comment]
That's pretty weird, I've never seen that happen. I'll look into it when I'm next using Windows.
