### ISSUE TITLE
UnsupportedOperationException

### ISSUE THREAD

**Issue by Hanson2258** [WPIRoboticsProjects/GRIP#980]
Thread[JavaFX Application Thread,5,main] threw an exception
## Stack Trace:
```java
java.lang.UnsupportedOperationException: Only 1 or 3 channel images can be shown, tried to show a 4 channel image
	at edu.wpi.grip.ui.util.ImageConverter.convert(ImageConverter.java:118)
	at edu.wpi.grip.ui.preview.ImageSocketPreviewView.lambda$null$0(ImageSocketPreviewView.java:31)
	at edu.wpi.grip.ui.util.GripPlatform.lambda$onJavaFXRunnerEvent$0(GripPlatform.java:74)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)

```

Selecting different cvt colour codes caused errors repeatidly.

**Comment by JLLeitschuh** [comment]
I think this is somewhat expected. The input image doesn't support certain conversions. Could you supply a screenshot of your pipeline?
